"""
Game data helpers for translating numeric identifiers into human-readable names.
"""

from typing import Optional

# Map ID -> Name derived from the ROM header list (valid locations only).
MAP_ID_TO_NAME = {
    0x00: "Pallet Town",
    0x01: "Viridian City",
    0x02: "Pewter City",
    0x03: "Cerulean City",
    0x04: "Lavender Town",
    0x05: "Vermilion City",
    0x06: "Celadon City",
    0x07: "Fuchsia City",
    0x08: "Cinnabar Island",
    0x09: "Pokemon League",
    0x0A: "Saffron City",
    0x0C: "Route 1",
    0x0D: "Route 2",
    0x0E: "Route 3",
    0x0F: "Route 4",
    0x10: "Route 5",
    0x11: "Route 6",
    0x12: "Route 7",
    0x13: "Route 8",
    0x14: "Route 9",
    0x15: "Route 10",
    0x16: "Route 11",
    0x17: "Route 12",
    0x18: "Route 13",
    0x19: "Route 14",
    0x1A: "Route 15",
    0x1B: "Route 16",
    0x1C: "Route 17",
    0x1D: "Route 18",
    0x1E: "Sea Route 19",
    0x1F: "Sea Route 20",
    0x20: "Sea Route 21",
    0x21: "Route 22",
    0x22: "Route 23",
    0x23: "Route 24",
    0x24: "Route 25",
    0x25: "Red's house 1F",
    0x26: "Red's house 2F",
    0x27: "Blue's house",
    0x28: "Professor Oak's Lab",
    0x29: "Pokemon Center (Viridian City)",
    0x2A: "Poke Mart (Viridian City)",
    0x2B: "School (Viridian City)",
    0x2C: "House 1 (Viridian City)",
    0x2D: "Gym (Viridian City)",
    0x2E: "Diglett's Cave (Route 2 entrance)",
    0x2F: "Gate (Viridian/Pewter, Route 2)",
    0x30: "Oak's Aide House 1 (Route 2)",
    0x31: "Gate (Route 2)",
    0x32: "Gate (Route 2/Viridian Forest)",
    0x33: "Viridian Forest",
    0x34: "Pewter Museum 1F",
    0x35: "Pewter Museum 2F",
    0x36: "Gym (Pewter City)",
    0x37: "House with Nidoran (Pewter City)",
    0x38: "Poke Mart (Pewter City)",
    0x39: "House with two Trainers (Pewter City)",
    0x3A: "Pokemon Center (Pewter City)",
    0x3B: "Mt. Moon (Route 3 entrance)",
    0x3C: "Mt. Moon",
    0x3D: "Mt. Moon",
    0x3E: "Trashed House (Cerulean)",
    0x3F: "Cerulean House (Trade/Jynx)",
    0x40: "Pokemon Center (Cerulean City)",
    0x41: "Gym (Cerulean City)",
    0x42: "Bike Shop (Cerulean City)",
    0x43: "Poke Mart (Cerulean City)",
    0x44: "Pokemon Center (Route 4)",
    0x45: "Trashed House Alt Music",
    0x46: "Saffron Gate (Route 5)",
    0x47: "Underground Path Entrance (Route 5)",
    0x48: "Daycare Center (Route 5)",
    0x49: "Saffron Gate (Route 6)",
    0x4A: "Underground Path Entrance (Route 6)",
    0x4B: "Underground Path Entrance Alt (Route 6)",
    0x4C: "Saffron Gate (Route 7)",
    0x4D: "Underground Path Entrance (Route 7)",
    0x4F: "Saffron Gate (Route 8)",
    0x50: "Underground Path Entrance (Route 8)",
    0x51: "Pokemon Center (Rock Tunnel)",
    0x52: "Rock Tunnel",
    0x53: "Power Plant",
    0x54: "Gate 1F (Route 11-12)",
    0x55: "Diglett's Cave (Vermilion entrance)",
    0x56: "Gate 2F (Route 11-12)",
    0x57: "Gate (Route 12-13)",
    0x58: "Sea Cottage (Bill's House)",
    0x59: "Pokemon Center (Vermilion City)",
    0x5A: "Pokemon Fan Club (Vermilion)",
    0x5B: "Poke Mart (Vermilion City)",
    0x5C: "Gym (Vermilion City)",
    0x5D: "House with Pidgey (Vermilion City)",
    0x5E: "Vermilion Harbor",
    0x5F: "S.S. Anne 1F",
    0x60: "S.S. Anne 2F",
    0x61: "S.S. Anne 3F",
    0x62: "S.S. Anne B1F",
    0x63: "S.S. Anne Deck",
    0x64: "S.S. Anne Kitchen",
    0x65: "S.S. Anne Captain's room",
    0x66: "S.S. Anne 1F Room",
    0x67: "S.S. Anne 2F Room",
    0x68: "S.S. Anne B1F Room",
    0x6C: "Victory Road Entrance (Route 23)",
    0x71: "Lance's room",
    0x76: "Hall of Fame",
    0x77: "Underground Path (Route 5-6)",
    0x78: "Champion Blue's room",
    0x79: "Underground Path (Route 7-8)",
    0x7A: "Celadon Dept. Store 1F",
    0x7B: "Celadon Dept. Store 2F",
    0x7C: "Celadon Dept. Store 3F",
    0x7D: "Celadon Dept. Store 4F",
    0x7E: "Celadon Dept. Store Rooftop",
    0x7F: "Celadon Dept. Store Lift",
    0x80: "Celadon Mansion 1F",
    0x81: "Celadon Mansion 2F",
    0x82: "Celadon Mansion 3F",
    0x83: "Celadon Mansion 4F",
    0x84: "Celadon Mansion 4F (Eevee)",
    0x85: "Pokemon Center (Celadon City)",
    0x86: "Gym (Celadon City)",
    0x87: "Rocket Game Corner",
    0x88: "Celadon Dept. Store 5F",
    0x89: "Prize Corner (Celadon City)",
    0x8A: "Restaurant (Celadon City)",
    0x8B: "House with Rocket (Celadon City)",
    0x8C: "Hotel (Celadon City)",
    0x8D: "Pokemon Center (Lavender Town)",
    0x8E: "Pokemon Tower 1F",
    0x8F: "Pokemon Tower 2F",
    0x90: "Pokemon Tower 3F",
    0x91: "Pokemon Tower 4F",
    0x92: "Pokemon Tower 5F",
    0x93: "Pokemon Tower 6F",
    0x94: "Pokemon Tower 7F",
    0x95: "Mr. Fuji's house",
    0x96: "Poke Mart (Lavender Town)",
    0x97: "House (Lavender Town)",
    0x98: "Poke Mart (Fuchsia City)",
    0x99: "House (Fuchsia City)",
    0x9A: "Pokemon Center (Fuchsia City)",
    0x9B: "Warden's house (Fuchsia City)",
    0x9C: "Safari Zone Gate",
    0x9D: "Gym (Fuchsia City)",
    0x9E: "Fuchsia Meeting Room",
    0x9F: "Seafoam Islands",
    0xA0: "Seafoam Islands",
    0xA1: "Seafoam Islands",
    0xA2: "Seafoam Islands",
    0xA3: "Vermilion Fishing Brother",
    0xA4: "Fuchsia Fishing Brother",
    0xA5: "Pokemon Mansion 1F",
    0xA6: "Gym (Cinnabar Island)",
    0xA7: "Pokemon Lab 1F",
    0xA8: "Pokemon Lab Trade Room",
    0xA9: "Pokemon Lab Scientists Room",
    0xAA: "Pokemon Lab Fossil Room",
    0xAB: "Pokemon Center (Cinnabar Island)",
    0xAC: "Poke Mart (Cinnabar Island)",
    0xAE: "Pokemon Center (Indigo Plateau)",
    0xAF: "Copycat's house 1F",
    0xB0: "Copycat's house 2F",
    0xB1: "Fighting Dojo",
    0xB2: "Gym (Saffron City)",
    0xB3: "House (Saffron City)",
    0xB4: "Poke Mart (Saffron City)",
    0xB5: "Silph Co. 1F",
    0xB6: "Pokemon Center (Saffron City)",
    0xB7: "Mr. Psychic's house",
    0xB8: "Gate 1F (Route 15)",
    0xB9: "Gate 2F (Route 15)",
    0xBA: "Gate 1F (Cycling Road)",
    0xBB: "Gate 2F (Cycling Road)",
    0xBC: "Secret house (Cycling Road)",
    0xBD: "Route 12 Fishing Brother",
    0xBE: "Gate 1F (Route 18)",
    0xBF: "Gate 2F (Route 18)",
    0xC0: "Seafoam Islands",
    0xC1: "Badges check gate (Route 22)",
    0xC2: "Victory Road",
    0xC3: "Gate 2F (Route 12)",
    0xC4: "House with HM advice (Vermilion)",
    0xC5: "Diglett's Cave",
    0xC6: "Victory Road",
    0xC7: "Rocket Hideout B1F",
    0xC8: "Rocket Hideout B2F",
    0xC9: "Rocket Hideout B3F",
    0xCA: "Rocket Hideout B4F",
    0xCB: "Rocket Hideout Lift",
    0xCF: "Silph Co. 2F",
    0xD0: "Silph Co. 3F",
    0xD1: "Silph Co. 4F",
    0xD2: "Silph Co. 5F",
    0xD3: "Silph Co. 6F",
    0xD4: "Silph Co. 7F",
    0xD5: "Silph Co. 8F",
    0xD6: "Pokemon Mansion 2F",
    0xD7: "Pokemon Mansion 3F",
    0xD8: "Pokemon Mansion B1F",
    0xD9: "Safari Zone East",
    0xDA: "Safari Zone North",
    0xDB: "Safari Zone West",
    0xDC: "Safari Zone Center",
    0xDD: "Safari Zone Rest House 1",
    0xDE: "Safari Zone Secret House",
    0xDF: "Safari Zone Rest House 2",
    0xE0: "Safari Zone Rest House 3",
    0xE1: "Safari Zone Rest House 4",
    0xE2: "Cerulean Cave",
    0xE3: "Cerulean Cave 1F",
    0xE4: "Cerulean Cave B1F",
    0xE5: "Name Rater's house",
    0xE6: "Cerulean City Gym Badge man",
    0xE8: "Rock Tunnel",
    0xE9: "Silph Co. 9F",
    0xEA: "Silph Co. 10F",
    0xEB: "Silph Co. 11F",
    0xEC: "Silph Co. Lift",
    0xF5: "Lorelei's room",
    0xF6: "Bruno's room",
    0xF7: "Agatha's room",
}

MAP_NAME_TO_ID = {name.lower(): mid for mid, name in MAP_ID_TO_NAME.items()}

# Pokemon ID (internal order) -> Name mapping (subset from ROM ID order)
POKEMON_ID_TO_NAME = {
    0x01: "Rhydon",
    0x02: "Kangaskhan",
    0x03: "Nidoran M",
    0x04: "Clefairy",
    0x05: "Spearow",
    0x06: "Voltorb",
    0x07: "Nidoking",
    0x08: "Slowbro",
    0x09: "Ivysaur",
    0x0A: "Exeggutor",
    0x0B: "Lickitung",
    0x0C: "Exeggcute",
    0x0D: "Grimer",
    0x0E: "Gengar",
    0x0F: "Nidoran F",
    0x10: "Nidoqueen",
    0x11: "Cubone",
    0x12: "Rhyhorn",
    0x13: "Lapras",
    0x14: "Arcanine",
    0x15: "Mew",
    0x16: "Gyarados",
    0x17: "Shellder",
    0x18: "Tentacool",
    0x19: "Gastly",
    0x1A: "Scyther",
    0x1B: "Staryu",
    0x1C: "Blastoise",
    0x1D: "Pinsir",
    0x1E: "Tangela",
    0x21: "Growlithe",
    0x22: "Onix",
    0x23: "Fearow",
    0x24: "Pidgey",
    0x25: "Slowpoke",
    0x26: "Kadabra",
    0x27: "Graveler",
    0x28: "Chansey",
    0x29: "Machoke",
    0x2A: "Mr. Mime",
    0x2B: "Hitmonlee",
    0x2C: "Hitmonchan",
    0x2D: "Arbok",
    0x2E: "Parasect",
    0x2F: "Psyduck",
    0x30: "Drowzee",
    0x31: "Golem",
    0x33: "Magmar",
    0x35: "Electabuzz",
    0x36: "Magneton",
    0x37: "Koffing",
    0x39: "Mankey",
    0x3A: "Seel",
    0x3B: "Diglett",
    0x3C: "Tauros",
    0x40: "Farfetch",
    0x41: "Venonat",
    0x42: "Dragonite",
    0x46: "Doduo",
    0x47: "Poliwag",
    0x48: "Jynx",
    0x49: "Moltres",
    0x4A: "Articuno",
    0x4B: "Zapdos",
    0x4C: "Ditto",
    0x4D: "Meowth",
    0x4E: "Krabby",
    0x52: "Vulpix",
    0x53: "Ninetales",
    0x54: "Pikachu",
    0x55: "Raichu",
    0x58: "Dratini",
    0x59: "Dragonair",
    0x5A: "Kabuto",
    0x5B: "Kabutops",
    0x5C: "Horsea",
    0x5D: "Seadra",
    0x60: "Sandshrew",
    0x61: "Sandslash",
    0x62: "Omanyte",
    0x63: "Omastar",
    0x64: "Jigglypuff",
    0x65: "Wigglytuff",
    0x66: "Eevee",
    0x67: "Flareon",
    0x68: "Jolteon",
    0x69: "Vaporeon",
    0x6A: "Machop",
    0x6B: "Zubat",
    0x6C: "Ekans",
    0x6D: "Paras",
    0x6E: "Poliwhirl",
    0x6F: "Poliwrath",
    0x70: "Weedle",
    0x71: "Kakuna",
    0x72: "Beedrill",
    0x74: "Dodrio",
    0x75: "Primeape",
    0x76: "Dugtrio",
    0x77: "Venomoth",
    0x78: "Dewgong",
    0x7B: "Caterpie",
    0x7C: "Metapod",
    0x7D: "Butterfree",
    0x7E: "Machamp",
    0x80: "Golduck",
    0x81: "Hypno",
    0x82: "Golbat",
    0x83: "Mewtwo",
    0x84: "Snorlax",
    0x85: "Magikarp",
    0x88: "Muk",
    0x8A: "Kingler",
    0x8B: "Cloyster",
    0x8D: "Electrode",
    0x8E: "Clefable",
    0x8F: "Weezing",
    0x90: "Persian",
    0x91: "Marowak",
    0x93: "Haunter",
    0x94: "Abra",
    0x95: "Alakazam",
    0x96: "Pidgeotto",
    0x97: "Pidgeot",
    0x98: "Starmie",
    0x99: "Bulbasaur",
    0x9A: "Venusaur",
    0x9B: "Tentacruel",
    0x9D: "Goldeen",
    0x9E: "Seaking",
    0xA3: "Ponyta",
    0xA4: "Rapidash",
    0xA5: "Rattata",
    0xA6: "Raticate",
    0xA7: "Nidorino",
    0xA8: "Nidorina",
    0xA9: "Geodude",
    0xAA: "Porygon",
    0xAB: "Aerodactyl",
    0xAD: "Magnemite",
    0xB0: "Charmander",
    0xB1: "Squirtle",
    0xB2: "Charmeleon",
    0xB3: "Wartortle",
    0xB4: "Charizard",
    0xB9: "Oddish",
    0xBA: "Gloom",
    0xBB: "Vileplume",
    0xBC: "Bellsprout",
    0xBD: "Weepinbell",
    0xBE: "Victreebel",
}

POKEMON_NAME_TO_ID = {name.lower(): pid for pid, name in POKEMON_ID_TO_NAME.items()}

# Item ID -> Name mapping (only valid/obtainable items)
ITEM_ID_TO_NAME = {
    0x01: "Master Ball",
    0x02: "Ultra Ball",
    0x03: "Great Ball",
    0x04: "Poke Ball",
    0x05: "Town Map",
    0x06: "Bicycle",
    0x08: "Safari Ball",
    0x09: "Pokedex",
    0x0A: "Moon Stone",
    0x0B: "Antidote",
    0x0C: "Burn Heal",
    0x0D: "Ice Heal",
    0x0E: "Awakening",
    0x0F: "Parlyz Heal",
    0x10: "Full Restore",
    0x11: "Max Potion",
    0x12: "Hyper Potion",
    0x13: "Super Potion",
    0x14: "Potion",
    0x15: "BoulderBadge",
    0x16: "CascadeBadge",
    0x17: "ThunderBadge",
    0x18: "RainbowBadge",
    0x19: "SoulBadge",
    0x1A: "MarshBadge",
    0x1B: "VolcanoBadge",
    0x1C: "EarthBadge",
    0x1D: "Escape Rope",
    0x1E: "Repel",
    0x1F: "Old Amber",
    0x20: "Fire Stone",
    0x21: "Thunderstone",
    0x22: "Water Stone",
    0x23: "HP Up",
    0x24: "Protein",
    0x25: "Iron",
    0x26: "Carbos",
    0x27: "Calcium",
    0x28: "Rare Candy",
    0x29: "Dome Fossil",
    0x2A: "Helix Fossil",
    0x2B: "Secret Key",
    0x2D: "Bike Voucher",
    0x2E: "X Accuracy",
    0x2F: "Leaf Stone",
    0x30: "Card Key",
    0x31: "Nugget",
    0x32: "PP Up",
    0x33: "Poke Doll",
    0x34: "Full Heal",
    0x35: "Revive",
    0x36: "Max Revive",
    0x37: "Guard Spec.",
    0x38: "Super Repel",
    0x39: "Max Repel",
    0x3A: "Dire Hit",
    0x3B: "Coin",
    0x3C: "Fresh Water",
    0x3D: "Soda Pop",
    0x3E: "Lemonade",
    0x3F: "S.S. Ticket",
    0x40: "Gold Teeth",
    0x41: "X Attack",
    0x42: "X Defend",
    0x43: "X Speed",
    0x44: "X Special",
    0x45: "Coin Case",
    0x46: "Oak's Parcel",
    0x47: "Itemfinder",
    0x48: "Silph Scope",
    0x49: "Poke Flute",
    0x4A: "Lift Key",
    0x4B: "Exp. All",
    0x4C: "Old Rod",
    0x4D: "Good Rod",
    0x4E: "Super Rod",
    0x4F: "PP Up",
    0x50: "Ether",
    0x51: "Max Ether",
    0x52: "Elixer",
    0x53: "Max Elixer",
    0xC4: "HM01 (Cut)",
    0xC5: "HM02 (Fly)",
    0xC6: "HM03 (Surf)",
    0xC7: "HM04 (Strength)",
    0xC8: "HM05 (Flash)",
    0xC9: "TM01 (Mega Punch)",
    0xCA: "TM02 (Razor Wind)",
    0xCB: "TM03 (Swords Dance)",
    0xCC: "TM04 (Whirlwind)",
    0xCD: "TM05 (Mega Kick)",
    0xCE: "TM06 (Toxic)",
    0xCF: "TM07 (Horn Drill)",
    0xD0: "TM08 (Body Slam)",
    0xD1: "TM09 (Take Down)",
    0xD2: "TM10 (Double-Edge)",
    0xD3: "TM11 (BubbleBeam)",
    0xD4: "TM12 (Water Gun)",
    0xD5: "TM13 (Ice Beam)",
    0xD6: "TM14 (Blizzard)",
    0xD7: "TM15 (Hyper Beam)",
    0xD8: "TM16 (Pay Day)",
    0xD9: "TM17 (Submission)",
    0xDA: "TM18 (Counter)",
    0xDB: "TM19 (Seismic Toss)",
    0xDC: "TM20 (Rage)",
    0xDD: "TM21 (Mega Drain)",
    0xDE: "TM22 (SolarBeam)",
    0xDF: "TM23 (Dragon Rage)",
    0xE0: "TM24 (Thunderbolt)",
    0xE1: "TM25 (Thunder)",
    0xE2: "TM26 (Earthquake)",
    0xE3: "TM27 (Fissure)",
    0xE4: "TM28 (Dig)",
    0xE5: "TM29 (Psychic)",
    0xE6: "TM30 (Teleport)",
    0xE7: "TM31 (Mimic)",
    0xE8: "TM32 (Double Team)",
    0xE9: "TM33 (Reflect)",
    0xEA: "TM34 (Bide)",
    0xEB: "TM35 (Metronome)",
    0xEC: "TM36 (Selfdestruct)",
    0xED: "TM37 (Egg Bomb)",
    0xEE: "TM38 (Fire Blast)",
    0xEF: "TM39 (Swift)",
    0xF0: "TM40 (Skull Bash)",
    0xF1: "TM41 (Softboiled)",
    0xF2: "TM42 (Dream Eater)",
    0xF3: "TM43 (Sky Attack)",
    0xF4: "TM44 (Rest)",
    0xF5: "TM45 (Thunder Wave)",
    0xF6: "TM46 (Psywave)",
    0xF7: "TM47 (Explosion)",
    0xF8: "TM48 (Rock Slide)",
    0xF9: "TM49 (Tri Attack)",
    0xFA: "TM50 (Substitute)",
}

# Build TM/HM alias lookups for move-name resolution
TMHM_ALIASES: dict[str, int] = {}
for item_id, name in ITEM_ID_TO_NAME.items():
    label = name.lower()
    if label.startswith("hm") or label.startswith("tm"):
        # e.g., "hm01 (cut)" -> aliases "hm01" and "cut"
        parts = label.split("(")
        code = parts[0].strip()
        move_name = parts[1].rstrip(")").strip() if len(parts) > 1 else None
        TMHM_ALIASES[code] = item_id
        if move_name:
            TMHM_ALIASES[move_name] = item_id

ITEM_NAME_TO_ID = {name.lower(): iid for iid, name in ITEM_ID_TO_NAME.items()}
ITEM_NAME_TO_ID.update(TMHM_ALIASES)

def map_id_to_name(map_id: Optional[int]) -> str:
    """Return a friendly name for the map id (fallback to 'Map {id}')."""
    if map_id is None:
        return "Unknown"
    return MAP_ID_TO_NAME.get(int(map_id), f"Map {int(map_id)}")


def map_name_to_id(name: Optional[str]) -> Optional[int]:
    """Return the map id for a given name (case-insensitive) or None."""
    if not name:
        return None
    return MAP_NAME_TO_ID.get(name.strip().lower())


def pokemon_id_to_name(pokemon_id: Optional[int]) -> str:
    """Return a friendly name for the internal Pokemon id (fallback to 'Pokemon {id}')."""
    if pokemon_id is None:
        return "Unknown"
    return POKEMON_ID_TO_NAME.get(int(pokemon_id), f"Pokemon {int(pokemon_id)}")


def pokemon_name_to_id(name: Optional[str]) -> Optional[int]:
    """Return the internal Pokemon id for a given name (case-insensitive) or None."""
    if not name:
        return None
    return POKEMON_NAME_TO_ID.get(name.strip().lower())


def item_id_to_name(item_id: Optional[int]) -> str:
    """Return a friendly name for an item id (fallback to 'Item {id}')."""
    if item_id is None:
        return "Unknown"
    return ITEM_ID_TO_NAME.get(int(item_id), f"Item {int(item_id)}")


def item_name_to_id(name: Optional[str]) -> Optional[int]:
    """Return the item id for a given name/alias (case-insensitive) or None."""
    if not name:
        return None
    return ITEM_NAME_TO_ID.get(name.strip().lower())
